INSERT OR IGNORE INTO Admin (id, email, password, name, createdAt) VALUES ('admin1', 'ricardo@ricardorautenberg.com.br', '$2b$12$QHj1Q6NoM1OnMovLsDrSIeAD/815IjoxdOPCiaUnoltkZv/kXycvS', 'Ricardo Rautenberg', datetime('now'));

INSERT OR IGNORE INTO SiteConfig (id, phone, whatsapp, instagram, email, aboutText, heroTitle, heroSubtitle) VALUES ('main', '+5511999999999', '+5511999999999', 'ricardo_rautenberg', 'contato@ricardorautenberg.com.br', '', 'Imoveis de Alto Padrao em Sao Paulo', 'Experiencia exclusiva em imoveis de luxo');

INSERT OR IGNORE INTO Property (id, title, slug, description, price, priceOnRequest, status, type, purpose, neighborhood, city, state, area, usableArea, bedrooms, suites, bathrooms, parkingSpots, floors, amenities, isFeatured, isOffMarket, createdAt, updatedAt) VALUES ('prop1', 'Cobertura Duplex no Itaim Bibi com Vista Panoramica', 'cobertura-duplex-itaim-bibi-vista-panoramica', 'Espetacular cobertura duplex com 450m2 no Itaim Bibi. Piscina privativa e vista panoramica.', 12500000, 0, 'available', 'penthouse', 'sale', 'Itaim Bibi', 'Sao Paulo', 'SP', 450, 380, 4, 4, 6, 6, 2, 'Piscina,Rooftop,Automacao Residencial,Home Cinema,Vista Panoramica', 1, 0, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO Property (id, title, slug, description, price, priceOnRequest, status, type, purpose, neighborhood, city, state, area, usableArea, bedrooms, suites, bathrooms, parkingSpots, floors, amenities, isFeatured, isOffMarket, createdAt, updatedAt) VALUES ('prop2', 'Apartamento de Luxo nos Jardins', 'apartamento-luxo-jardins-lazer-completo', 'Apartamento sofisticado nos Jardins. 280m2 com projeto assinado.', 8900000, 0, 'available', 'apartment', 'sale', 'Jardim Paulista', 'Sao Paulo', 'SP', 280, 240, 3, 3, 4, 4, NULL, 'Piscina,Academia,Spa,Salao de Festas', 1, 0, datetime('now'), datetime('now'));

INSERT OR IGNORE INTO Property (id, title, slug, description, price, priceOnRequest, status, type, purpose, neighborhood, city, state, area, usableArea, bedrooms, suites, bathrooms, parkingSpots, floors, amenities, isFeatured, isOffMarket, createdAt, updatedAt) VALUES ('prop3', 'Casa em Condominio Fechado no Morumbi', 'casa-condominio-fechado-morumbi', 'Residencia imponente no Morumbi. 600m2 em terreno de 1.000m2.', NULL, 1, 'available', 'house', 'sale', 'Morumbi', 'Sao Paulo', 'SP', 1000, 600, 5, 5, 7, 8, NULL, 'Piscina,Quadra de Tenis,Churrasqueira Gourmet,Car Gallery', 1, 0, datetime('now'), datetime('now'));
